baseurl: "parloerapp"
url: "https://kasperdyrvig.github.io"

collections:
  dictionary:
  grupper:
    output: true
  parloer:
    output: true
  lektioner:
    output: true
  moduler:
    output: true
